EDL/EDL/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic import ListView, DetailView
from posts.models import Articles

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainApp.urls'), name='index'),
    url(r'^news/', include('posts.urls')),
]

EDL/mainApp/urls.py
from django.conf.urls import url,include
from . import views
from django.views.generic import ListView, DetailView
from posts.models import Articles

app_name = 'mainApp'
urlpatterns=[
    #url(r'^$',views.index, name="index"),
    #url(r'^$', views.MainView.as_view(), name='index'),
    url(r'^$', ListView.as_view(queryset=Articles.objects.all().order_by("-date"),
    template_name="mainApp/homePage.html"), name='lsit_posts'),
    url(r'auth/$', views.login ),
    url(r'logout/$', views.logout),
    url(r'register/$', views.RegisterFormView.as_view()),
    #url(r'profile/(?P<pk>\d+)/$', ListView.as_view(queryset=Articles.objects.all().order_by("-date"),
    #template_name="mainApp/profile.html")),
    url(r'add_post/', views.AddPost.as_view(), name='post_create'),
    url(r'profile/(?P<pk>\d+)/$', views.ViewProfile.as_view(), name='profile')
]

EDL/posts/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic import ListView, DetailView
from posts.models import Articles
from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^(?P<pk>\d+)/$',DetailView.as_view(model= Articles, template_name = "posts/post.html")),
    url(r'^edit_post/(?P<pk>\d+)/$', views.EditPost.as_view(), name='update-post'),

]

EDL/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
url(r'^$', views.MainView.as_view()),
url(r'^login/$', views.login ),
url(r'^logout/$', views.logout),
url(r'^register/$', views.RegisterFormView.as_view())
]

EDL/mainApp/models.py
from django.db import models

EDL/posts/models.py
from django.db import models


class Articles(models.Model):
    title = models.CharField(max_length = 120)
    post = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

def __str__(self):
    return self.title

EDL/users/models.py
from django.db import models

class Human(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=256)
 #Create your models here.

EDL/posts/forms.py
from django import forms
from .models import Articles
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'post', 'author']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'post' : forms.Textarea(attrs={'class':'form-control'}),
        }

EDL/mainApp/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout
from users.models import Human
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib import auth
from django.shortcuts import render_to_response, redirect
from django.template.context_processors import csrf
from posts.forms import PostForm
from django.contrib.auth.hashers import make_password
from posts.models import Articles
from django.views.generic import View, ListView, UpdateView
from posts.models import *
from mainApp import urls
from django.contrib.auth.models import User

# Create your views here.

class MainView(TemplateView):
    template_name = 'mainApp/homePage.html'
    def get(self,request):
        if request.user.is_authenticated:
            humans = Human.objects.all()
            ctx={}
            ctx['humans'] = humans
            return render(request , self.template_name, ctx)

        else:
            return render(request , self.template_name, {})
class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/auth/"
    template_name = "mainApp/register.html"

    def form_valid(self,form):
        forma = form.save(commit = False)
        form.password = make_password(forma.password)
        form.save()
        return super(RegisterFormView, self).form_valid(form)

class AddPost(View):
    def get(self, request):
        form= PostForm()
        return render(request,'addPost.html', context={'form':form})
    def post(self, request):
         bound_form = PostForm(request.POST)
         if bound_form.is_valid():
            new_post = bound_form.save(commit = False)
            new_post.user= request.user
            new_post.save()
            return redirect('/')
         return render(request, 'addPost.html', context={'form':bound_form})

class ViewProfile(View):
    template_name = 'mainApp/profile.html'
    def get(self, request, pk):
        model = Articles
        m = model.objects.all()
        for obj in m:
            if obj.author.id == int(pk):
                usr = obj.author
        return render(request, self.template_name, context={'usr':usr, 'models':m})
        #user = model.objects.get(author.id == pk)
        #current_user = model.objects.get(author)
        #context ={
    #        'list_posts':current_user
    #    }
    #    return render(request, template_name, context)



def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username',)
        password = request.POST.get('password',)
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            args['login_error']='Пользователь не найден'
            return render_to_response('login.html', args)
    else:
        return render_to_response('login.html', args)

def logout(request):
    auth.logout(request)
    return redirect('/')

EDL/posts/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib import auth
from . import models
from django.core.paginator import Paginator
from django.template.context_processors import csrf
from django.views.generic import View, UpdateView
from posts.forms import PostForm
from posts.models import Articles
from posts import urls
from django.urls import reverse
from mainApp import urls

class EditPost(UpdateView):
    model = Articles
    form_class= PostForm
    template_name = "posts/edit_post.html"
    def get_success_url(self):
        return reverse('mainApp:lsit_posts')

EDL/users/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout
from users.models import Human
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib import auth
from django.shortcuts import render_to_response, redirect
# Create your views here.

class MainView(TemplateView):
    template_name = 'mainApp/homepage.html'
    def get(self,request):
        if request.user.is_authenticated:
            humans = Human.objects.all()
            ctx={}
            ctx['humans'] = humans
            return render(request , self.template_name, ctx)

        else:
            return render(request , self.template_name, {})
class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "users/register.html"

    def form_valid(self,form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

def login(request):
    args = {}
    args.update(request)
    if request.POST:
        username = request.POST.get('username',)
        password = request.POST.get('password',)
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            args['login_error']='Пользователь не найден'
            return render_to_response('login.html', args)
    else:
        return render_to_response('login.html', args)
    return 0;
def logout():
    auth.loggout(request)
    return redirect('/')


# class LoginFormView(FormView):
#    form_class = AuthenticationForm
#    template_name = "users/authentication.html"
#    def form_valid(self,form):
#    return super(LoginFormView,self).form_valid(form)

EDL/mainApp/templates/login.html
{% extends 'mainApp/wrapper.html' %}

{% block login %}
  <div class='large-offset-3 large-6 columns'>
    <form action="/auth/" method="post">
      {% csrf_token %}
      <label for='username'>Имя пользователя</label>
      <input type='text' name='username' id='username'>
      <label for='password'>Пароль</label>
      <input type='text' name='password' id='password'>
      {% if login_error %}
        <label class='error'>{{ login_error }}</label>
      {% endif %}
      <input class='button' type="submit" value="Войти">
    </form>
  </div>
{% endblock %}

EDL/mainApp/templates/mainApp/homePage.html
{% extends "mainApp/wrapper.html" %}
{% block content %}
   <nav class="navbar navbar-expand-lg navbar-default bg-light" >
        <div class="container">
        <ul class="nav nav-tabs" role="tablist">
          <li><a class="nav-link active" href="#news" role="tab" data-toggle="tab"><font color=#4B2455><small>Все темы</small></font></a></li>
        </ul>
      </div>

    </nav>
<div class="row" style="padding:7%">
  <div class="col-lg-6">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="news">{% include "posts/posts.html" %}</div>
    </div>
  </div>
  <div class="col-lg-3">
  </div>
</div>
{% endblock %}

EDL/mainApp/templates/mainApp/profile.html
{% extends "mainApp/wrapper.html" %}

{% block content %}

<div class="container-fluid">
<div class="row">
  <div class="col-lg-6">
    <div class='row'>
      <div class='col-lg-5' >
        <h1 style="color:#4B2455">Логин:<i>{{ usr }}</i> </h1>
      </div>
      <div class='col-lg-7'></div>
    </div>
      <div>
    <a class="btn btn-success btn-md" style="background-color:#55A29F" href="/add_post/"><font color="white">Создать пост</font></a>
  </div>
  </div>
<div  class="col-lg-6">
  {% for post in models %}
  {% if post.author == usr %}
    <a href="/news/{{post.id}}"><h4>{{ post.title }}</h4></a>
    <h6>{{post.date|date:"d-m-Y"}}</h6>
  {% endif %}
  {% endfor %}

</div>
</div>
{% endblock %}

EDL/mainApp/templates/mainApp/register.html
{% extends "mainApp/wrapper.html" %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Зарегистрироваться</button>
{% endblock %}

EDL/mainApp/templates/mainApp/wrapper.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>EDLife</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
  <body>
    <header>
        <div class="navbar navbar-fixed-top" style="background-color:#4B2455">
              <div class="row" style="width:100%; height:100%;">
                  <div class="navbar-header col-lg-9 col-md-7 col-xs-3" style="padding-left:7%">
                      <a class="navbar-brand" href="/"><font color="white"><b color="white">EDLife</b></font></a>
                  </div>
                  <div class="btn-group col-lg-3 col-md-5 col-xs-9">
                      <div calss="btn-toolbar" role="toolbar">
                        {% if user.is_authenticated %}
                         <a class="btn btn-light btn-md" style="background-color:#55A29F" href="/user/logout/"><font color="white">Выйти</font></a>
                         <a class="btn btn-light btn-md" style="background-color:#FFFFFF" href="/user/profile/{{user.id}}"><font color=#4B2455>Профиль</font></a>
                        {% else %}
                        <a class="btn btn-light btn-md" style="background-color:#55A29F" href="/user/auth/"><font color="white">Войти</font></a>
                        <a class="btn btn-light btn-md" style="background-color:#FFFFFF" href="/user/register/"><font color=#4B2455>Регистрация</font></a>
                        {% endif %}
                      </div>
                  </div>
              </div>
        </div>
      </header>
      <div class="container-fluid">
    {% block content %}
    {% block login %}{% endblock %}
    {% endblock %}
  </div>
<footer><hr/>Все права защищены</footer>
  </body>
</html>

EDL/posts/templates/addPost.html
{% extends "mainApp/wrapper.html" %}
{% block content %}
<div class='container-fluid'>
<form action="{% url 'mainApp:post_create' %}" method="post">
  {% csrf_token %}
  {% for field in form %}
      <div class='form-group'>
        {% if fields.errors %}
          <div class='alert alert-danger'>
            {{ field.errors }}
          </div>
        {% endif %}
        {{field.label}}
        {{ field }}
      </div>
  {% endfor %}
  <input class='button' type="submit" value="Сохранить">
</form>
</div>
{% endblock %}

EDL/posts/templates/posts/edit_post.html
{% extends "mainApp/wrapper.html" %}
{% block content %}
<div class='container-fluid'>
<form action="{% url 'posts:update-post' pk=articles.id %}" method="post">
  {% csrf_token %}
  {% for field in form %}
      <div class='form-group'>
        {% if fields.errors %}
          <div class='alert alert-danger'>
            {{ field.errors }}
          </div>
        {% endif %}
        {{field.label}}
        {{ field }}
      </div>
  {% endfor %}
  <input class='button' type="submit" value="Сохранить">
</form>
</div>
{% endblock %}

EDL/posts/templates/posts/post.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="container-fluid">
<div class="row">
  <div class="col-lg-6"/>
<div  class="col-lg-6">
    <h4 class="text-info">{{articles.title}}</h4>
    <h5 align="center"><i>{{articles.post|safe|linebreaks}}</i></h5>
    <h6 align="right">{{articles.date|date:"d-m-Y H:i:s"}}</h6>
    </div>
    {% if articles.author == user %}
    <a class="btn btn-light btn-md" style="background-color:#55A29F" href="{% url 'posts:update-post' articles.id %}"><font color="white">Редактировать</font></a>
    {% endif %}
</div>
</div>
{% endblock %}

EDL/posts/templates/posts/posts.html
  {% for pos in object_list %}

    <a href="/news/{{pos.id}}"><h4>{{pos.title}}</h4></a>
    <i>{{pos.post}}</i>
    <h6>{{pos.date|date:"d-m-Y"}} Создал:<a href="{% url 'mainApp:profile' pos.author.id %}"> {{pos.author}}</a></h6>
  {% endfor %}